typography_spectrum: 0.8006175267510116
color:
  brandStrength: 0.16505977557972074
  lightness: 0.14968582056462765
  saturation: 0.6579398340545595
  rhythmicContrast: 0.4914253717288375
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
opengraph:
  appId: 'https://www.facebook.com/joris.swinkels'
  type: FB
layout_spectrum: 0.383120596408844
author:
  name: joris swinkels
  email: joris@swinkels.be
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5d9c5cb4-9c26-48f0-8841-be5d0e503ba0.png
name: de bewuste samenleving
navigation:
  - name: Contact
    id: cd8b8fea-0a46-4cc5-9e24-450ea84541ed
    type: content
  - name: cc.com
    url: creativeconsciosness.com
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/93e2381e-365c-417d-85c0-b24024e767f0.png
title: de bewuste samen-leving
description: the conscious society
