typography_spectrum: 0.2963783321902156
color:
  brandStrength: 0.16505977557972074
  lightness: 0.14968582056462765
  saturation: 0.6579398340545595
  rhythmicContrast: 0.4914253717288375
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
opengraph:
  appId: 'https://www.facebook.com/joris.swinkels'
  type: FB
layout_spectrum: 0.383120596408844
author:
  name: joris swinkels
  email: joris@swinkels.be
logo: null
name: de bewuste samenleving
navigation:
  - name: Ik en jij
    id: b5ae5c31-b9ab-4fdf-8ec3-3a032f7418f0
    type: content
  - name: Wij allen
    id: f51e16e1-0e3c-4a7a-8416-ad3534e61e79
    type: content
  - name: 'Business '
    id: afaa1159-9a2e-471a-b02a-ba7e3d5a1b0b
    type: content
  - name: Fundamenten
    id: 39edd0a3-6754-4d4d-b8fd-a536bd9d303d
    type: content
  - name: Contact
    id: cd8b8fea-0a46-4cc5-9e24-450ea84541ed
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/93e2381e-365c-417d-85c0-b24024e767f0.png
title: de bewuste samen-leving
description: the conscious society
